imrunicorn/api/urls.py
from django.urls import path, include
from . import views
from content_collection import views as c_views
# from meme_leach import views as meme_leach_views
from rest_framework import routers
from django.views.generic import TemplateView
# from api.views import ChartData as GroundHogChartData
from groundhog_logbook.views import ChartDataBySex
# from api.views import ChartDataTest
from .views import ActivityLogViewSet

# similar to object based url building
router = routers.DefaultRouter()
# router.get_api_root_view().cls.__name__ = "BenSpelledABC: API"
# router.get_api_root_view().cls.__doc__ = "Becoming the backbone to wonderland."

router.register('activity_log/activity', views.ActivityViewSet)
router.register('activity_log/activity_log', views.ActivityLogViewSet)
router.register('activity_log/activity_photo_validation', views.ActivityPhotoValidationViewSet)

router.register('announcements/what_is_new', views.WhatIsNewView)
router.register('announcements/main_page_blurbs', views.MainPageBlurbsView)
router.register('announcements/page_blurb_overrides', views.PageBlurbOverridesView)

router.register('content_collection/insults', views.ContentCollectionInsultsViewSet)

router.register('deer_wait_list/Recipient', views.DeerWaitListRecipient)
router.register('deer_wait_list/MeatCut', views.DeerWaitListMeatCut)
router.register('deer_wait_list/Flavor', views.DeerWaitListFlavor)
router.register('deer_wait_list/RequestedOrder', views.DeerWaitListRequestedOrder)

router.register('loaddata/Owner', views.Owner)
router.register('loaddata/Caliber', views.LoadDataCaliber)
router.register('loaddata/Firearm', views.LoadDataFirearm)
router.register('loaddata/Powder', views.LoadDataPowder)
router.register('loaddata/Projectile', views.LoadDataProjectile)
router.register('loaddata/Brass', views.LoadDataBrass)
router.register('loaddata/Primer', views.LoadDataPrimer)
router.register('loaddata/HandLoad', views.LoadDataHandLoad)
router.register('loaddata/EstimatedDope', views.LoadDataEstimatedDope)

router.register('groundhog_logbook/Location', views.LocationView)
router.register('groundhog_logbook/RemovalsByLocation', views.RemovalsByLocationView)
# router.register('groundhog_logbook/chart/data/test', ChartDataTest.as_view(), basename=ChartDataTest)

router.register('deer_harvest_logbook/Harvests', views.HarvestsView)
router.register('deer_harvest_logbook/HarvestsPhotos', views.HarvestsPhotosView)

router.register('shooting_challenge/ChallengeEvent', views.ChallengeEventViewSet)
router.register('shooting_challenge/ChallengePhoto', views.ChallengePhotoViewSet)

router.register('accounts', views.Accounts)

router.register('meme_leach', views.MemeLeachViewSet)
# router.register('meme_leach/<str:subreddit>', views.MemeLeachViewSet.random_meme_by_subreddit_name)

# router.register('sensor_reading', c_views.sensor_readings)

# /api/docker/hook
# router.register('docker_hub_hook', views.docker_hub_webhook)


# HyperlinkedModelSerializer doesn't like namespace addressing for the 'url' to work
# app_name = 'api'
urlpatterns = [
    # path('DeerWaitListRecipient/', views.DeerWaitListRecipient, name='DeerWaitListRecipient'),
    # path("activity_log", ActivityLogViewSet.as_view(), name='activity_log'),
    path('', include(router.urls)),
    path('docker_hub_hook/', views.docker_hub_webhook, name='docker_hub_webhook'),
    path('sensor_reading/', c_views.sensor_readings, name='sensor_readings'),

    path('meme_leach/<str:subreddit>', views.random_meme_by_subreddit),
]

imrunicorn/deer_harvest_logbook/urls.py
from django.urls import path, include
from . import views
from .views import ChartDataByTime, ChartDataBySex, ChartDataByMonth, ChartDataByYear, \
    ChartDataByRemover, ChartDataByTemperature, ChartDataByCloudLevel

app_name = 'deer_harvest_logbook'
urlpatterns = [
    path('', views.page_all_harvests, name='all_harvests'),
    path('by_shooter/', views.page_all_harvests, name='all_harvests'),
    path('by_shooter/<int:shooter_pk>', views.page_all_harvests_by_shooter_pk, name='all_harvests'),

    path('point_system/', views.page_point_system, name='point_system'),
    path('point_system/show_points', views.page_point_system_show_points, name='point_system_show_points'),

    path('charts/', views.page_charts_by_time, name='page_charts'),

    path('charts/by_time/', views.page_charts_by_time, name='charts_by_time'),
    path('api/chart/by_time/data/', ChartDataByTime.as_view()),

    path('charts/by_sex/', views.page_charts_by_sex, name='charts_by_sex'),
    path('api/chart/by_sex/data/', ChartDataBySex.as_view()),

    path('charts/by_month/', views.page_charts_by_month, name='charts_by_month'),
    path('api/chart/by_month/data/', ChartDataByMonth.as_view()),

    path('charts/by_year/', views.page_charts_by_year, name='charts_by_year'),
    path('api/chart/by_year/data/', ChartDataByYear.as_view()),

    path('charts/by_cloud_level/', views.page_charts_by_cloud_level, name='charts_by_cloud_level'),
    path('api/chart/by_cloud_level/data/', ChartDataByCloudLevel.as_view()),

    path('charts/by_temperature/', views.page_charts_by_temperature, name='charts_by_temperature'),
    path('api/chart/by_temperature/data/', ChartDataByTemperature.as_view()),

    path('charts/by_remover/', views.page_charts_by_remover, name='charts_by_remover'),
    path('api/chart/by_remover/data/', ChartDataByRemover.as_view()),


    # path('locations/', views.page_all_groundhog_locations, name='all_groundhog_locations'),
    # path('charts/', views.page_charts, name='page_charts'),
    # path('by_shooter/', views.page_all_groundhog_removals, name='all_groundhog_removals'),
    # path('by_shooter/<int:shooter_pk>', views.page_all_groundhog_removals_by_shooter_pk, name='all_groundhog_removals'),
    # path('removal_scoreboard/', views.page_groundhog_removals_scoreboard, name='groundhog_removal_scoreboard'),

    # path('api/chart/', ChartData.as_view()),

    # path('detail/', views.page_news_by_pk, name='news_by_pk'),
    # path('detail/<int:news_pk>', views.page_news_by_pk, name='news_by_pk'),
]

imrunicorn/imrunicorn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from datetime import datetime
from django.conf import settings
# from . import forms, views
from announcements.get_news import get_news, get_version_json
from django.conf import settings
from django.conf.urls.static import static
from . import forms, views


# app_name = 'base_skipped_for_now'
urlpatterns = [

    path('test/', views.page_test_layout, name='test_layout'),

    path('api-auth/', include('rest_framework.urls')),
    path('api/weather/', views.page_api_weather, name='page_api_weather'),
    path('qr/about/', views.page_qr_about, name='qr_about'),
    path('admin/', admin.site.urls),
    path('', views.page_home, name='home'),

    path('access_denied_groups', views.page_access_denied_groups, name='access_denied_groups'),

    path('page_hits/', views.page_page_hits, name='page_hits'),

    path('activity_log/', include('activity_log.urls')),
    path('announcements/', include('announcements.urls')),
    path('api/', include('api.urls')),
    path('load_data/', include('loaddata.urls')),
    # path('farm_invite/', include('farminvite.urls')),
    path('polls/', include('polls.urls')),
    path('shooting_logbook/', include('shooting_logbook.urls')),
    path('groundhog_logbook/', include('groundhog_logbook.urls')),
    path('deer_harvest_logbook/', include('deer_harvest_logbook.urls')),
    path('deer_wait_list/', include('deer_wait_list.urls')),
    path('admin_toolbox/', include('admin_toolbox.urls')),
    path('status_watcher/', include('status_watcher.urls')),
    path('content_collection/', include('content_collection.urls')),
    path('call_of_the_wild/', include('call_of_the_wild.urls')),
    path('shooting_challenge/', include('shooting_challenge.urls')),
    path('dcsa_info/', include('dcsa_info.urls')),
    path('bingo/', include('bingo.urls')),
    path('puppy_fostering/', include('puppy_fostering.urls')),
    path('meme_leach/', include('meme_leach.urls')),


    # path('contact/', views.contact, name='contact'),
    # path('about/', views.about, name='about'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('login/',
         LoginView.as_view
             (
             template_name='imrunicorn/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Log In',
                 'copy_year': datetime.now().year,
                 'release': get_version_json(),
                 'blurb': 'I am not allowing new accounts at this time.',
                 'no_accounts_blurb': 'If you have an account and need a reset, you know how to reach me..',
             }
         ),
         name='login'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# # https://docs.djangoproject.com/en/2.0/topics/http/views/#customizing-error-views
# handler404 = 'YOUR_APP_NAME.views.handler404'

handler404 = 'imrunicorn.views.handler404'
handler403 = 'imrunicorn.views.handler403'
handler500 = 'imrunicorn.views.handler500'

imrunicorn/loaddata/urls.py
from django.urls import path
from . import views

# router = routers.DefaultRouter()
# router.register('roll', views.RollView)
# router.register('student', views.StudentView)
# router.register('courses', views.CourseView)

app_name = 'load_data'
urlpatterns = [
    path('', views.page_loads, name='home'),

    path('foot_pound_calculator/', views.page_foot_pound_calc, name='foot_pound_calculator'),

    # page_loads_details
    path('loads/', views.page_loads, name='loads'),
    path('loads/<int:load_pk>', views.page_loads_details, name='loads'),
    path('loads/<str:load_type>', views.page_loads_by_type, name='loads'),

    path('estimated_dope/<int:load_pk>', views.page_estimated_dope, name='page_estimated_dope'),
    path('estimated_dope/', views.page_estimated_dope, name='page_estimated_dope'),

    path('firearm_detail/<int:firearm_pk>', views.page_firearm_detail, name='page_firearm_detail'),
    path('firearm_detail/', views.page_firearm_detail, name='page_firearm_detail'),

    path('caliber_detail/<int:caliber_pk>', views.page_caliber_detail, name='page_caliber_detail'),
    path('caliber_detail/', views.page_caliber_detail, name='page_caliber_detail'),

    path('toolbox/', views.home_create_view, name='create_home'),
    path('toolbox/create_caliber/', views.caliber_create_view, name='create_caliber'),
    path('toolbox/create_powder/', views.powder_create_view, name='create_powder'),
    path('toolbox/create_projectile/', views.projectile_create_view, name='create_projectile'),
    path('toolbox/create_firearm/', views.firearm_create_view, name='create_firearm'),

    path('docker/', views.docker_update_test, name='docker_update_test'),

]

imrunicorn/deer_harvest_logbook/models.py
from django.db import models
from datetime import date
from django.db import models
from loaddata.models import Firearm, HandLoad
from decimal import Decimal
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from imrunicorn.functions import get_weather


# Create your models here.


class HarvestPhoto(models.Model):
    kill_shot = models.ImageField(upload_to='uploads/deer_shots/', null=True, blank=True)
    photo_date = models.DateField(default=date.today)

    def __str__(self):
        return "%s - %s - %s" % (self.id, self.photo_date, self.kill_shot.url)

    class Meta:
        ordering = ('-photo_date', '-id')


class DeerManagementPermit(models.Model):
    issued_to = models.ForeignKey(User, on_delete=models.CASCADE)
    permit_id = models.CharField(max_length=10, default='06375')

    def __str__(self):
        return "%s - %s" % (self.issued_to, self.permit_id)

    class Meta:
        ordering = ('permit_id', )


class Harvests(models.Model):
    shooter = models.ForeignKey(User, related_name='deer_harvest_logbook_shooter', on_delete=models.CASCADE, null=True)
    harvest_date = models.DateField(default=date.today)
    harvest_time = models.TimeField(null=True)
    dnr_confirmation = models.CharField(blank=True, default=None, max_length=50, null=True)
    harvest_score = models.IntegerField(null=True, blank=True)
    bonus_for_not_unpleasant = models.BooleanField(default=False, null=True, blank=True)
    # crop_damage_permit = models.BooleanField(default=False, null=True, blank=True)
    deer_management_permit_id = models.ForeignKey(DeerManagementPermit, on_delete=models.CASCADE, null=True, blank=True)
    firearm = models.ForeignKey(Firearm, related_name='deer_harvest_logbook_firearm', on_delete=models.CASCADE)
    load = models.ForeignKey(HandLoad, related_name='deer_harvest_logbook_hand_load', on_delete=models.CASCADE)
    estimated_weight_lbs = models.DecimalField(max_digits=5, decimal_places=2, default=100.25)
    # excessive_wound_cavity = models.BooleanField(default=False)
    shot_distance_yards = models.DecimalField(max_digits=4, decimal_places=0, default=200)
    yards_ran = models.DecimalField(max_digits=4, decimal_places=1, default=0)
    extra_info = models.TextField(blank=True, null=True)  # i like big comments...
    kill_shot = models.ImageField(upload_to='uploads/deer_shots/', null=True, blank=True)
    kill_shot_two = models.ImageField(upload_to='uploads/deer_shots/', null=True, blank=True)
    removal_photos = models.ManyToManyField(HarvestPhoto, blank=True)

    UNKNOWN = 'UNKNOWN'
    MALE = 'MALE'
    FEMALE = 'FEMALE'

    SEX_CHOICES = [
        (UNKNOWN, 'Unknown'),
        (MALE, 'Male'),
        (FEMALE, 'Female'),
    ]
    sex = models.CharField(
        max_length=20,
        choices=SEX_CHOICES,
        default=UNKNOWN,
    )

    CLEAR_SKY = 'Clear Sky'
    FEW_CLOUDS = 'Few Clouds'
    SCATTERED_CLOUDS = 'Scattered Clouds'
    BROKEN_CLOUDS = 'Broken Clouds'
    SHOWER_RAIN = "Shower/Rain"
    RAIN = "Rain"
    THUNDERSTORM = "Thunderstorm"
    SNOW = "Snow"
    MIST = "Mist"
    UNKNOWN = 'Unknown'

    cloud_level_choices = [
        (CLEAR_SKY, 'Clear Sky'),
        (FEW_CLOUDS, 'Few Clouds'),
        (SCATTERED_CLOUDS, 'Scattered Clouds'),
        (BROKEN_CLOUDS, 'Broken Clouds'),
        (SHOWER_RAIN, 'Shower/Rain'),
        (RAIN, 'Rain'),
        (THUNDERSTORM, 'Thunderstorm'),
        (SNOW, 'Snow'),
        (MIST, 'Mist'),
        (UNKNOWN, 'Unknown'),
    ]
    cloud_level = models.CharField(
        max_length=20,
        choices=cloud_level_choices,
        default=UNKNOWN,
    )
    wind_speed = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    wind_dir = models.IntegerField(default=1)
    estimated_temperature = models.IntegerField(
        null=True,
        default=-49,
        validators=[
            MaxValueValidator(120),
            MinValueValidator(-50)
        ]
    )

    def save(self, *args, **kwargs):
        if self.wind_speed == 0.00 and self.wind_dir == 1 and self.estimated_temperature == -49:
            # only fetch weather if it appears to be defaults
            weather = get_weather(self, 39.619718, -77.023989)
            # weather = get_weather(self, self.location.latitude, self.location.longitude)
            self.estimated_temperature = weather['temperature']
            self.cloud_level = weather['description']
            self.wind_speed = weather['wind_speed']
            self.wind_dir = weather['wind_dir']
        super(Harvests, self).save(*args, **kwargs)

    def __str__(self):
        return "%s - %s (%s yards from '%s')" % (self.harvest_date,
                                                 self.shooter,
                                                 self.shot_distance_yards,
                                                 self.estimated_weight_lbs)

    class Meta:
        verbose_name = 'Harvest'
        verbose_name_plural = 'Harvests'
        ordering = ('-harvest_date', '-harvest_time', 'shooter', 'shot_distance_yards')

imrunicorn/deer_harvest_logbook/templates/deer_harvest_logbook/all_harvests.html
{% extends "imrunicorn/layout.html" %}
{% load static %}

{% block extra_head %}

{% endblock %}


{% block content %}
{% load humanize %}


<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">{% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            The robot that lives at this website is AFK and hasn't picked a page blurb yet.
        {% endif %}</p>

    <p class="lead"><strong>Location: </strong>{{ weather.full_response.name }}<br />
        <strong>Temp:</strong> {{ weather.temperature }}&deg;F <i>(Feels Like: {{ weather.feels_like }}&deg;F)</i><br />
        <strong>Wind Speed:</strong> {{ weather.wind_speed }}mph
        <strong>Wind Direction:</strong>
        {{ comment }}
        <a href="https://www.sasquatchstation.com/images/dual-compass-rose.png" target="_blank"></a>
        {{ endcomment }}

        {{ weather.wind_dir }}&deg;
        ({{ weather.wind_dir_word }})<br />
        <strong>Sky:</strong> {{ weather.description }}
    </p>

</div>

{% if all_news != None %}

<div class="row ben_format_pretty">
    <div class='post-body entry-content' id='post-body-3156955225064661913' itemprop='description articleBody'>
        <div style="text-align: left;font-family:times new roman;">

            {% for news in all_news %}
                <b>Harvest Date:</b> {{ news.harvest_date }}<br />
                <b>Harvest Time:</b> {{ news.harvest_time }}<br />


                {% if news.estimated_temperature > -49 %}
                    <b>Estimated Temperature:</b> {{ news.estimated_temperature }}&deg;F<br />
                {% else %}
                    <b>Estimated Temperature:</b> No data<br />
                {% endif %}

                <b>Cloud Level:</b> {{ news.cloud_level }}<br />

                <b>Shooter:</b>
                    <a href="{% url 'deer_harvest_logbook:all_harvests' %}{{ news.shooter.pk }}">
                    {{ news.shooter.userprofile.preferred_display_name|default:news.shooter.username }}
                    </a><br />

                {% comment %}
                assume it was NOT a DMP if its not specifically listed as such.
                {% endcomment %}

                {% if news.deer_management_permit_id != None %}
                    {% if unrestricted_user %}
                        <b>Deer Management Permit:</b> {{ news.deer_management_permit_id.permit_id }}<br />
                    {% else %}
                        <b>Deer Management Permit:</b> True<br />
                    {% endif %}
                {% endif %}


                <b>Firearm Info:</b><a href="{% url 'load_data:page_firearm_detail' %}{{ news.firearm.pk }}">{{ news.firearm }}</a><br />

                <b>Load Detail:</b>{% if user.is_authenticated %} {{ news.load }}{% else %} <i>(Logged In Users Only)</i></i>{% endif %}<br />
                <b>Estimated Weight (lbs):</b> {{ news.estimated_weight_lbs }}<br />

                {% if news.sex == "MALE" %}
                    <b>Sex:</b> {{ news.sex }} - <i class="fas fa-mars"></i><br />
                {% elif news.sex == "FEMALE" %}
                    <b>Sex:</b> {{ news.sex }} - <i class="fas fa-venus"></i><br />
                {% else %}
                    <b>Sex:</b> {{ news.sex }} - <i class="far fa-question-circle"></i><br />
                {% endif %}

                <b>Shot Distance Yards:</b> {{ news.shot_distance_yards }}<br />
                <b>Yards Ran:</b> {{ news.yards_ran }}<br />
                <b>Score:</b> {{ news.harvest_score }} {% if news.bonus_for_not_unpleasant %} + 1 (bonus) {% endif %}<br />

                {% if news.extra_info %}
                <b>Extra Info:</b><br /> {% autoescape off %}{{ news.extra_info }}{% endautoescape %}</br>
                {% endif %}

                {% if news.kill_shot.url != None%}
                        <b>Image 1:</b><br />
                        <a href="{{ news.kill_shot.url }}" target="_blank"><img src="{{ news.kill_shot.url }}" style="width: 30%" /></a><br />
                {% endif %}

                {% if news.kill_shot_two.url != None%}
                        <b>Image 2:</b><br />
                        <a href="{{ news.kill_shot_two.url }}" target="_blank"><img src="{{ news.kill_shot_two.url }}" style="width: 30%" /></a><br />
                {% endif %}


                {% for bonus_photo in news.removal_photos.all %}
                        <b>Bonus Image: {{ forloop.counter }}</b><br />
                        <a href="{{ bonus_photo.kill_shot.url }}" target="_blank"><img src="{{ bonus_photo.kill_shot.url }}" style="width: 30%" /></a><br />
                {% endfor %}


                {% if forloop.last  == False %}
                    <hr />
                {% else %}
                    <br />
                {% endif %}

            {% endfor %}
        </div>

    </div>
</div>


    <div align="center">
    <p align="center">
        {% if all_news.has_other_pages %}
        <ul class="pagination">
            {% if all_news.has_previous %}
                <li><a href="?page={{ all_news.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="disabled"><span>&laquo;</span></li>
            {% endif %}

            <li><a href="?page=1">Newest</a></li>
            {% for l in all_news.paginator.page_range %}
                {% if l <= all_news.number|add:5 and l >= all_news.number|add:-5 %}
                    <li><a href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
                {% endif %}
            {% endfor %}
            <li><a href="?page={{all_news.paginator.num_pages}}">Oldest</a></li>

            {% if all_news.has_next %}
                <li><a href="?page={{ all_news.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
        {% endif %}
    </p>
        </div>

{% endif %}


{% endblock %}

imrunicorn/deer_harvest_logbook/templates/deer_harvest_logbook/deer_graphic_generic.html
{% extends "imrunicorn/layout.html" %}

<script>
{% block jquery %}
var endpoint = '{{ graph_api_node }}'
var defaultData = []
var labels = [];
$.ajax({
    method: "GET",
    url: endpoint,

    success: function(data){
        console.log(data)
        labels = data.labels
        defaultData = data.default
        setChart()
    },
    error: function(error_data){
        console.log("error")
        console.log(error_data)
    }
})

function setChart(){
    var ctx = document.getElementById("myChart");
    var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: labels,
        datasets: [{
            label: '{{ graph_header }}',
            data: defaultData,

            backgroundColor: [
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)'
            ],
            borderColor: [
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});

}

{% endblock %}
</script>

{% block content %}

<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">
            {% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            The robot that lives at this website is AFK and hasn't picked a page blurb yet.
        {% endif %}
    </p>
</div>

<div class="row ben_format_pretty">
        <div align="center">
        <div>
            <a class="dropdown-item" href="{% url 'deer_harvest_logbook:charts_by_sex' %}"> By Sex</a> |
            <a class="dropdown-item" href="{% url 'deer_harvest_logbook:charts_by_time' %}"> By Time</a> |
            <a class="dropdown-item" href="{% url 'deer_harvest_logbook:charts_by_month' %}"> By Month</a> |
            <a class="dropdown-item" href="{% url 'deer_harvest_logbook:charts_by_year' %}"> By Year</a> |
            <a class="dropdown-item" href="{% url 'deer_harvest_logbook:charts_by_temperature' %}"> By Temperature</a> |
            <a class="dropdown-item" href="{% url 'deer_harvest_logbook:charts_by_cloud_level' %}"> By Cloud Level</a> |
            <a class="dropdown-item" href="{% url 'deer_harvest_logbook:charts_by_remover' %}"> By Remover</a>
        </div>
    </div>
</div>

<br />

<div class="row ben_format_pretty">
    <div align="center">
        <div>{{ graph_message }}</div>
        <div class='col-sm-12'>
            <div class='col-sm-6' style="width:100%"><canvas id="myChart"></canvas></div>
        </div>
    </div>
</div>

{% endblock content %}