imrunicorn/activity_log/urls.py
from django.urls import path, include
# from views import ChartDataScoreByUser
from . import views
from .views import ChartDataScoreByUser


app_name = 'activity_log'
urlpatterns = [
    path('', views.page_blank, name='blank'),
    path('task_list', views.page_task_list, name='task_list'),
    path('tasks_per_user', views.page_tasks_per_user, name='tasks_per_user'),
    path('current_points', views.page_current_points, name='current_points'),

    path('photo_validation', views.page_photo_validation, name='photo_validation'),

    path('charts/scoreboard/', views.page_scoreboard_by_user, name='scoreboard_by_user'),
    path('api/chart/scoreboard/by_user/data/', ChartDataScoreByUser.as_view()),

]

imrunicorn/api/urls.py
from django.urls import path, include
from . import views
from content_collection import views as c_views
# from meme_leach import views as meme_leach_views
from rest_framework import routers
from django.views.generic import TemplateView
# from api.views import ChartData as GroundHogChartData
from groundhog_logbook.views import ChartDataBySex
# from api.views import ChartDataTest
from .views import ActivityLogViewSet

# similar to object based url building
router = routers.DefaultRouter()
# router.get_api_root_view().cls.__name__ = "BenSpelledABC: API"
# router.get_api_root_view().cls.__doc__ = "Becoming the backbone to wonderland."

router.register('activity_log/activity', views.ActivityViewSet)
router.register('activity_log/activity_log', views.ActivityLogViewSet)
router.register('activity_log/activity_photo_validation', views.ActivityPhotoValidationViewSet)

router.register('announcements/what_is_new', views.WhatIsNewView)
router.register('announcements/main_page_blurbs', views.MainPageBlurbsView)
router.register('announcements/page_blurb_overrides', views.PageBlurbOverridesView)

router.register('content_collection/insults', views.ContentCollectionInsultsViewSet)

router.register('deer_wait_list/Recipient', views.DeerWaitListRecipient)
router.register('deer_wait_list/MeatCut', views.DeerWaitListMeatCut)
router.register('deer_wait_list/Flavor', views.DeerWaitListFlavor)
router.register('deer_wait_list/RequestedOrder', views.DeerWaitListRequestedOrder)

router.register('loaddata/Owner', views.Owner)
router.register('loaddata/Caliber', views.LoadDataCaliber)
router.register('loaddata/Firearm', views.LoadDataFirearm)
router.register('loaddata/Powder', views.LoadDataPowder)
router.register('loaddata/Projectile', views.LoadDataProjectile)
router.register('loaddata/Brass', views.LoadDataBrass)
router.register('loaddata/Primer', views.LoadDataPrimer)
router.register('loaddata/HandLoad', views.LoadDataHandLoad)
router.register('loaddata/EstimatedDope', views.LoadDataEstimatedDope)

router.register('groundhog_logbook/Location', views.LocationView)
router.register('groundhog_logbook/RemovalsByLocation', views.RemovalsByLocationView)
# router.register('groundhog_logbook/chart/data/test', ChartDataTest.as_view(), basename=ChartDataTest)

router.register('deer_harvest_logbook/Harvests', views.HarvestsView)
router.register('deer_harvest_logbook/HarvestsPhotos', views.HarvestsPhotosView)

router.register('shooting_challenge/ChallengeEvent', views.ChallengeEventViewSet)
router.register('shooting_challenge/ChallengePhoto', views.ChallengePhotoViewSet)

router.register('accounts', views.Accounts)

router.register('meme_leach', views.MemeLeachViewSet)
# router.register('meme_leach/<str:subreddit>', views.MemeLeachViewSet.random_meme_by_subreddit_name)

# router.register('sensor_reading', c_views.sensor_readings)

# /api/docker/hook
# router.register('docker_hub_hook', views.docker_hub_webhook)


# HyperlinkedModelSerializer doesn't like namespace addressing for the 'url' to work
# app_name = 'api'
urlpatterns = [
    # path('DeerWaitListRecipient/', views.DeerWaitListRecipient, name='DeerWaitListRecipient'),
    # path("activity_log", ActivityLogViewSet.as_view(), name='activity_log'),
    path('', include(router.urls)),
    path('docker_hub_hook/', views.docker_hub_webhook, name='docker_hub_webhook'),
    path('sensor_reading/', c_views.sensor_readings, name='sensor_readings'),

    path('meme_leach/<str:subreddit>', views.random_meme_by_subreddit),
]

imrunicorn/imrunicorn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from datetime import datetime
from django.conf import settings
# from . import forms, views
from announcements.get_news import get_news, get_version_json
from django.conf import settings
from django.conf.urls.static import static
from . import forms, views


# app_name = 'base_skipped_for_now'
urlpatterns = [

    path('test/', views.page_test_layout, name='test_layout'),

    path('api-auth/', include('rest_framework.urls')),
    path('api/weather/', views.page_api_weather, name='page_api_weather'),
    path('qr/about/', views.page_qr_about, name='qr_about'),
    path('admin/', admin.site.urls),
    path('', views.page_home, name='home'),

    path('access_denied_groups', views.page_access_denied_groups, name='access_denied_groups'),

    path('page_hits/', views.page_page_hits, name='page_hits'),

    path('activity_log/', include('activity_log.urls')),
    path('announcements/', include('announcements.urls')),
    path('api/', include('api.urls')),
    path('load_data/', include('loaddata.urls')),
    # path('farm_invite/', include('farminvite.urls')),
    path('polls/', include('polls.urls')),
    path('shooting_logbook/', include('shooting_logbook.urls')),
    path('groundhog_logbook/', include('groundhog_logbook.urls')),
    path('deer_harvest_logbook/', include('deer_harvest_logbook.urls')),
    path('deer_wait_list/', include('deer_wait_list.urls')),
    path('admin_toolbox/', include('admin_toolbox.urls')),
    path('status_watcher/', include('status_watcher.urls')),
    path('content_collection/', include('content_collection.urls')),
    path('call_of_the_wild/', include('call_of_the_wild.urls')),
    path('shooting_challenge/', include('shooting_challenge.urls')),
    path('dcsa_info/', include('dcsa_info.urls')),
    path('bingo/', include('bingo.urls')),
    path('puppy_fostering/', include('puppy_fostering.urls')),
    path('meme_leach/', include('meme_leach.urls')),


    # path('contact/', views.contact, name='contact'),
    # path('about/', views.about, name='about'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('login/',
         LoginView.as_view
             (
             template_name='imrunicorn/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Log In',
                 'copy_year': datetime.now().year,
                 'release': get_version_json(),
                 'blurb': 'I am not allowing new accounts at this time.',
                 'no_accounts_blurb': 'If you have an account and need a reset, you know how to reach me..',
             }
         ),
         name='login'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# # https://docs.djangoproject.com/en/2.0/topics/http/views/#customizing-error-views
# handler404 = 'YOUR_APP_NAME.views.handler404'

handler404 = 'imrunicorn.views.handler404'
handler403 = 'imrunicorn.views.handler403'
handler500 = 'imrunicorn.views.handler500'

imrunicorn/activity_log/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


class Activity(models.Model):
    name = models.CharField(max_length=150, default=None, blank=True, null=True)
    description = models.TextField(blank=True, null=True)  # i like big comments...
    sfw = models.BooleanField(default=False)
    transaction_amount = models.IntegerField(
        null=True,
        default=-2,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(-100)
        ]
     )

    def __str__(self):
        return "[cost: %s] %s" % (self.transaction_amount, self.name)

    class Meta:
        ordering = ('-transaction_amount', 'name')
        verbose_name = 'Activity'
        verbose_name_plural = 'Activities'


class ActivityLog(models.Model):
    actor = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE, null=True)
    date = models.DateField(default=date.today)
    time = models.TimeField(null=True)
    actor_comments = models.TextField(blank=True, null=True)  # i like big comments...
    approved = models.BooleanField(default=False)

    def __str__(self):
        return "[%s %s] %s - %s" % (self.date, self.time, self.actor, self.activity.name)

    class Meta:
        ordering = ('-date', '-time')
        verbose_name = 'Activity Log'
        verbose_name_plural = 'Activity Logs'


class ActivityPhotoValidation(models.Model):
    activity_log = models.ForeignKey(ActivityLog, on_delete=models.CASCADE, null=True)
    caption = models.CharField(max_length=350, default=None, blank=True, null=True)
    photo_proof = models.ImageField(upload_to='uploads/activity_log/', null=True, blank=True)

    def __str__(self):
        return "%s" % self.activity_log

    class Meta:
        ordering = ('-activity_log', 'id')
        verbose_name = 'Activity Photo Validation'
        verbose_name_plural = 'Activity Photo Validations'

imrunicorn/activity_log/views.py
from django.contrib.auth.decorators import permission_required
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.views import APIView

from announcements.get_news import get_version_json, get_page_blurb_override, get_page_secret
from groundhog_logbook.functions import groundhog_removal_scoreboard
from imrunicorn.functions import step_hit_count_by_page
from datetime import datetime
from django.shortcuts import render
from imrunicorn.decorators import allowed_groups
from .functions import activity_list, activity_scoreboard, activity_tasks_per_user, \
    activity_photo_validation, activity_scoreboard_by_user

from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import DjangoModelPermissions


# @allowed_groups(allowed_groupname_list=['activity_log_viewer', 'activity_log_tasker'])
def page_blank(request):
    step_hit_count_by_page(request.path)
    context = {
        "copy_year": datetime.now().year,
        'release': get_version_json(),
        "title": "Activity Log: home",
        "blurb": get_page_blurb_override('activity_log/home/'),
    }
    return render(request, "activity_log/home.html", context)


@permission_required('activity_log.view_activity', login_url='/login', raise_exception=True)
def page_task_list(request):
    step_hit_count_by_page(request.path)
    data = activity_list()
    context = {
        "copy_year": datetime.now().year,
        'release': get_version_json(),
        "title": "Activity Log: Task List",
        "blurb": get_page_blurb_override('activity_log/task_list/'),
        "secret": get_page_secret('activity_log/task_list/'),
        "data": data,
    }
    return render(request, "activity_log/activity_list.html", context)


# @allowed_groups(allowed_groupname_list=['activity_log_viewer', 'activity_log_tasker'])
@permission_required('activity_log.view_activitylog', login_url='/login', raise_exception=True)
def page_tasks_per_user(request):
    step_hit_count_by_page(request.path)
    data = activity_tasks_per_user(request)
    context = {
        "copy_year": datetime.now().year,
        'release': get_version_json(),
        "title": "Activity Log: Tasks Per User",
        "blurb": get_page_blurb_override('activity_log/tasks_per_user/'),
        "data": data,
    }
    return render(request, "activity_log/tasks_per_user.html", context)


# @allowed_groups(allowed_groupname_list=['activity_log_viewer', 'activity_log_tasker'])
@permission_required('activity_log.view_activitylog', login_url='/login', raise_exception=True)
def page_current_points(request):
    step_hit_count_by_page(request.path)
    data = activity_tasks_per_user()
    context = {
        "copy_year": datetime.now().year,
        'release': get_version_json(),
        "title": "Activity Log: Current Points",
        "blurb": get_page_blurb_override('activity_log/current_points/'),
        "data": data,
    }
    return render(request, "activity_log/tasks_per_user.html", context)


# @allowed_groups(allowed_groupname_list=['activity_log_viewer', 'activity_log_tasker'])
@permission_required('activity_log.view_activityphotovalidation', login_url='/login', raise_exception=True)
def page_photo_validation(request):
    step_hit_count_by_page(request.path)
    data = activity_photo_validation(request)

    context = {
        "copy_year": datetime.now().year,
        'release': get_version_json(),
        "title": "Activity Log: Photo Validation",
        "blurb": get_page_blurb_override('activity_log/photo_validation/'),
        "data": data,
    }
    return render(request, "activity_log/photo_validation.html", context)


@permission_required('activity_log.view_activitylog', login_url='/login', raise_exception=True)
def page_scoreboard_by_user(request):
    step_hit_count_by_page(request.path)

    context = {
        "graph_api_node": '/activity_log/api/chart/scoreboard/by_user/data/',
        "graph_header": "# points (By User)",
        "graph_message": "Running total (no resets)",
        "copy_year": datetime.now().year,
        'release': get_version_json(),
        "title": "Scoreboard Line Charts",
        "blurb": get_page_blurb_override('activity_log/charts/scoreboard/'),
    }
    return render(request, "activity_log/activity_log_graphic_generic.html", context)


class ChartDataScoreByUser(APIView):
    authentication_classes = []
    permission_classes = []

    def get(self, request, format=None):
        by_hour = activity_scoreboard_by_user()
        labels = []
        default_items = []

        for item in by_hour:
            if item['actor__userprofile__preferred_display_name']:
                labels.append(item['actor__userprofile__preferred_display_name'])
            else:
                labels.append(item['actor__username'])

        for item in by_hour:
            default_items.append(item['points'])

        data = {
            "labels": labels,
            "default": default_items,
            "endpoint": "/activity_log/api/chart/scoreboard/by_user/data/",
            "graph_title": "# of Groundhog Removals (By Temperature)"
        }
        return Response(data)

imrunicorn/activity_log/templates/activity_log/activity_list.html
{% extends "imrunicorn/layout.html" %}

{% block extra_head %}

{% endblock %}



{% block content %}
<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">{% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            The robot that lives at this website is AFK and hasn't picked a page blurb yet.
        {% endif %}</p>
</div>


<div class="row ben_format_pretty">
        <div align="center">
        <div>
            {% include 'activity_log/chart_menu.html' %}
        </div>
    </div>
</div>

<br />

<div class="row ben_format_pretty">

    <div>
        {% autoescape off %}{{ secret }}{% endautoescape %}
    </div>
    <br />

        <table align="center" border="1" width="95%">
            <tr bgcolor="#808080">
                <th bgcolor="808080" style="text-align: center">
                 KP/AP
             </th>
                <th bgcolor="808080" style="text-align: center">
                 Activity Name
             </th>
            <th bgcolor="808080" style="text-align: center">
                Description
            </th>

    {% for record in data %}
        <tr bgcolor="#BEBEBE">
              <td style="padding-left:10px">
                  {{ record.transaction_amount }}
              </td>
            <td style="padding-left:10px">
                  {{ record.name }}
              </td>
            <td style="padding-left:10px">
                  {{ record.description }}
              </td>
        </tr>
    {% endfor %}
        </table>
</div>

{% endblock %}

imrunicorn/activity_log/templates/activity_log/activity_log_graphic_generic.html
{% extends "imrunicorn/layout.html" %}

<script>
{% block jquery %}
var endpoint = '{{ graph_api_node }}'
var defaultData = []
var labels = [];
$.ajax({
    method: "GET",
    url: endpoint,

    success: function(data){
        console.log(data)
        labels = data.labels
        defaultData = data.default
        setChart()
    },
    error: function(error_data){
        console.log("error")
        console.log(error_data)
    }
})

function setChart(){
    var ctx = document.getElementById("myChart");
    var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: labels,
        datasets: [{
            label: '{{ graph_header }}',
            data: defaultData,

            backgroundColor: [
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)'
            ],
            borderColor: [
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});

}

{% endblock %}
</script>

{% block content %}

<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">
            {% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            The robot that lives at this website is AFK and hasn't picked a page blurb yet.
        {% endif %}
    </p>
</div>


<div class="row ben_format_pretty">
        <div align="center">
        <div>
            {% include 'activity_log/chart_menu.html' %}
        </div>
    </div>
</div>

<br />

<div class="row ben_format_pretty">
    <div align="center">
        <div>{{ graph_message }}</div>
        <div class='col-sm-12'>
            <div class='col-sm-6' style="width:100%"><canvas id="myChart"></canvas></div>
        </div>
    </div>
</div>

{% endblock content %}

imrunicorn/activity_log/templates/activity_log/chart_menu.html
<a class="dropdown-item" href="{% url 'activity_log:task_list' %}"> Task List</a> |
{% comment %} <a class="dropdown-item" href="{% url 'activity_log:scoreboard' %}"> Task Scoreboard</a> |{% endcomment %}
<a class="dropdown-item" href="{% url 'activity_log:photo_validation' %}"> Task Photo Validation</a> |
<a class="dropdown-item" href="{% url 'activity_log:tasks_per_user' %}"> Tasks By User</a> |
<a class="dropdown-item" href="{% url 'activity_log:scoreboard_by_user' %}"> Scoreboard</a>

imrunicorn/activity_log/templates/activity_log/home.html
{% extends "imrunicorn/layout.html" %}

{% block extra_head %}

{% endblock %}



{% block content %}
<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">{% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            The robot that lives at this website is AFK and hasn't picked a page blurb yet.
        {% endif %}</p>
</div>


<div class="row ben_format_pretty">
        <div align="center">
        <div>
            {% include 'activity_log/chart_menu.html' %}
        </div>
    </div>
</div>

<br />

<div class="row ben_format_pretty">
    <div align="center">
        Brace yourself, you haven't over clicked anything yet!
    </div>
</div>

{% endblock %}

imrunicorn/activity_log/templates/activity_log/photo_validation.html
{% extends "imrunicorn/layout.html" %}

{% block extra_head %}

{% endblock %}



{% block content %}
<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">{% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            The robot that lives at this website is AFK and hasn't picked a page blurb yet.
        {% endif %}</p>
</div>


<div class="row ben_format_pretty">
        <div align="center">
        <div>
            {% include 'activity_log/chart_menu.html' %}
        </div>
    </div>
</div>

<br />

<div class="row ben_format_pretty">
    {% for record in data %}
        {% ifchanged record.activity_log.id %}

            {% if forloop.first  == False %}
                <hr style="height:2px;border-width:0;color:gray;background-color:red" />
            {% else %}
                <br />
            {% endif %}

            {% comment %}
            <b>Log Entry:</b> {{ record.activity_log.id }}<br />
            {% endcomment %}
            <b>Date:</b> {{ record.activity_log.date }}<br />
            <b>Time:</b> {{ record.activity_log.time }}<br />
            <b>Actor:</b>
    {{ record.activity_log.actor.userprofile.preferred_display_name|default:record.activity_log.actor.username }}<br />

            <b>Name:</b> {{ record.activity_log.activity.name }}<br />
            <b>Description:</b> {{ record.activity_log.activity.description }}<br />
            <br />
            <b>Photo Caption:</b> {{ record.caption }}<br />
            <b>Photo Proof:</b>
    <a href="{{ record.photo_proof.url }}" target="_blank">
        <img src="{{ record.photo_proof.url }}" style="width: 30%" ></a><br />
        {% else %}
            <br /><br />
            <b>Photo Caption:</b> {{ record.caption }}<br />
            <b>Photo Proof:</b>
    <a href="{{ record.photo_proof.url }}" target="_blank">
        <img src="{{ record.photo_proof.url }}" style="width: 30%" ></a><br />
        {% endifchanged %}

    {% endfor %}

</div>

<div align="center">
    {% if data.has_other_pages %}
    <ul class="pagination">
        {% if data.has_previous %}
            <li><a href="?page={{ all_news.previous_page_number }}">&laquo;</a></li>
        {% else %}
            <li class="disabled"><span>&laquo;</span></li>
        {% endif %}

        <li><a href="?page=1">Newest</a></li>
        {% for l in data.paginator.page_range %}
            {% if l <= data.number|add:5 and l >= data.number|add:-5 %}
                <li><a href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
            {% endif %}
        {% endfor %}
        <li><a href="?page={{all_news.paginator.num_pages}}">Oldest</a></li>

        {% if data.has_next %}
            <li><a href="?page={{ all_news.next_page_number }}">&raquo;</a></li>
        {% else %}
            <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
    {% endif %}
</div>



{% endblock %}

imrunicorn/activity_log/templates/activity_log/tasks_per_user.html
{% extends "imrunicorn/layout.html" %}

{% block extra_head %}

{% endblock %}



{% block content %}
<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">{% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            The robot that lives at this website is AFK and hasn't picked a page blurb yet.
        {% endif %}</p>
</div>


<div class="row ben_format_pretty">
        <div align="center">
        <div>
            {% include 'activity_log/chart_menu.html' %}
        </div>
    </div>
</div>

<br />

<div class="row ben_format_pretty">

        <table align="center" border="1" width="95%">
            <tr bgcolor="#808080">
                <th bgcolor="808080" style="text-align: center">
                 User
             </th>
                <th bgcolor="808080" style="text-align: center">
                 Timestamp
             </th>
            <th bgcolor="808080" style="text-align: center">
                KP/AP
            </th>
            <th bgcolor="808080" style="text-align: center">
                Description
            </th>
            <th bgcolor="808080" style="text-align: center">
                Comments
            </th>

    {% for record in data %}
        <tr bgcolor="#BEBEBE">
              <td style="padding-left:10px">
                  {{ record.actor.userprofile.preferred_display_name |default:record.actor.username }}
              </td>
            <td style="padding-left:10px">
                  {{ record.date }} @ {{ record.time }}
              </td>
            <td style="padding-left:10px">
                  {{ record.activity.transaction_amount }}
              </td>
            <td style="padding-left:10px">
                  {{ record.activity.description }}
              </td>
            <td style="padding-left:10px">
                  {{ record.actor_comments }}
              </td>
        </tr>
    {% endfor %}
        </table>
</div>


<div align="center">
    {% if data.has_other_pages %}
    <ul class="pagination">
        {% if data.has_previous %}
            <li><a href="?page={{ all_news.previous_page_number }}">&laquo;</a></li>
        {% else %}
            <li class="disabled"><span>&laquo;</span></li>
        {% endif %}

        <li><a href="?page=1">Newest</a></li>
        {% for l in data.paginator.page_range %}
            {% if l <= data.number|add:5 and l >= data.number|add:-5 %}
                <li><a href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
            {% endif %}
        {% endfor %}
        <li><a href="?page={{all_news.paginator.num_pages}}">Oldest</a></li>

        {% if data.has_next %}
            <li><a href="?page={{ all_news.next_page_number }}">&raquo;</a></li>
        {% else %}
            <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
    {% endif %}
</div>

{% endblock %}