imrunicorn/api/urls.py
from django.urls import path, include
from . import views
from content_collection import views as c_views
# from meme_leach import views as meme_leach_views
from rest_framework import routers
from django.views.generic import TemplateView
# from api.views import ChartData as GroundHogChartData
from groundhog_logbook.views import ChartDataBySex
# from api.views import ChartDataTest
from .views import ActivityLogViewSet

# similar to object based url building
router = routers.DefaultRouter()
# router.get_api_root_view().cls.__name__ = "BenSpelledABC: API"
# router.get_api_root_view().cls.__doc__ = "Becoming the backbone to wonderland."

router.register('activity_log/activity', views.ActivityViewSet)
router.register('activity_log/activity_log', views.ActivityLogViewSet)
router.register('activity_log/activity_photo_validation', views.ActivityPhotoValidationViewSet)

router.register('announcements/what_is_new', views.WhatIsNewView)
router.register('announcements/main_page_blurbs', views.MainPageBlurbsView)
router.register('announcements/page_blurb_overrides', views.PageBlurbOverridesView)

router.register('content_collection/insults', views.ContentCollectionInsultsViewSet)

router.register('deer_wait_list/Recipient', views.DeerWaitListRecipient)
router.register('deer_wait_list/MeatCut', views.DeerWaitListMeatCut)
router.register('deer_wait_list/Flavor', views.DeerWaitListFlavor)
router.register('deer_wait_list/RequestedOrder', views.DeerWaitListRequestedOrder)

router.register('loaddata/Owner', views.Owner)
router.register('loaddata/Caliber', views.LoadDataCaliber)
router.register('loaddata/Firearm', views.LoadDataFirearm)
router.register('loaddata/Powder', views.LoadDataPowder)
router.register('loaddata/Projectile', views.LoadDataProjectile)
router.register('loaddata/Brass', views.LoadDataBrass)
router.register('loaddata/Primer', views.LoadDataPrimer)
router.register('loaddata/HandLoad', views.LoadDataHandLoad)
router.register('loaddata/EstimatedDope', views.LoadDataEstimatedDope)

router.register('groundhog_logbook/Location', views.LocationView)
router.register('groundhog_logbook/RemovalsByLocation', views.RemovalsByLocationView)
# router.register('groundhog_logbook/chart/data/test', ChartDataTest.as_view(), basename=ChartDataTest)

router.register('deer_harvest_logbook/Harvests', views.HarvestsView)
router.register('deer_harvest_logbook/HarvestsPhotos', views.HarvestsPhotosView)

router.register('shooting_challenge/ChallengeEvent', views.ChallengeEventViewSet)
router.register('shooting_challenge/ChallengePhoto', views.ChallengePhotoViewSet)

router.register('accounts', views.Accounts)

router.register('meme_leach', views.MemeLeachViewSet)
# router.register('meme_leach/<str:subreddit>', views.MemeLeachViewSet.random_meme_by_subreddit_name)

# router.register('sensor_reading', c_views.sensor_readings)

# /api/docker/hook
# router.register('docker_hub_hook', views.docker_hub_webhook)


# HyperlinkedModelSerializer doesn't like namespace addressing for the 'url' to work
# app_name = 'api'
urlpatterns = [
    # path('DeerWaitListRecipient/', views.DeerWaitListRecipient, name='DeerWaitListRecipient'),
    # path("activity_log", ActivityLogViewSet.as_view(), name='activity_log'),
    path('', include(router.urls)),
    path('docker_hub_hook/', views.docker_hub_webhook, name='docker_hub_webhook'),
    path('sensor_reading/', c_views.sensor_readings, name='sensor_readings'),

    path('meme_leach/<str:subreddit>', views.random_meme_by_subreddit),
]

imrunicorn/content_collection/urls.py
from django.urls import path, include
from . import views

app_name = 'content_collection'
urlpatterns = [
    path('', views.page_home, name='home'),

    path('videos/', views.page_video_list, name='video_list'),
    path('videos/<int:video_pk>', views.page_latest_video_by_pk, name='video_list'),

    path('videos/latest', views.page_latest_video, name='videos_latest'),

    path('carousel', views.page_carousel, name='carousel'),
    path('carousel/recent', views.page_carousel_recent, name='carousel_recent'),

    path('dnd5e', views.page_dnd5e_list, name='dnd5e_list'),
    path('fantasy_grounds', views.page_fantasy_grounds_list, name='fantasy_grounds_list'),

    path('insult', views.leach_insult, name='insult'),
    path('insult_list_all', views.insult_list_all, name='insult_list_all'),

    path('secrets_list_all', views.secrets_list_all, name='secrets_list_all'),

    path('buzz_words_or_phrases_list_all', views.buzz_words_or_phrases_list_all, name='buzz_words_or_phrases_list_all'),

    # path('dnd5e/<int:dnd5e_pk>', views.page_dnd5e_list_by_pk, name='dnd5e_list'),

    path('sketches/', views.page_sketch_list, name='sketches'),
    path('sketches/<int:sketch_pk>', views.page_sketch_by_pk, name='sketches'),

]

imrunicorn/imrunicorn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from datetime import datetime
from django.conf import settings
# from . import forms, views
from announcements.get_news import get_news, get_version_json
from django.conf import settings
from django.conf.urls.static import static
from . import forms, views


# app_name = 'base_skipped_for_now'
urlpatterns = [

    path('test/', views.page_test_layout, name='test_layout'),

    path('api-auth/', include('rest_framework.urls')),
    path('api/weather/', views.page_api_weather, name='page_api_weather'),
    path('qr/about/', views.page_qr_about, name='qr_about'),
    path('admin/', admin.site.urls),
    path('', views.page_home, name='home'),

    path('access_denied_groups', views.page_access_denied_groups, name='access_denied_groups'),

    path('page_hits/', views.page_page_hits, name='page_hits'),

    path('activity_log/', include('activity_log.urls')),
    path('announcements/', include('announcements.urls')),
    path('api/', include('api.urls')),
    path('load_data/', include('loaddata.urls')),
    # path('farm_invite/', include('farminvite.urls')),
    path('polls/', include('polls.urls')),
    path('shooting_logbook/', include('shooting_logbook.urls')),
    path('groundhog_logbook/', include('groundhog_logbook.urls')),
    path('deer_harvest_logbook/', include('deer_harvest_logbook.urls')),
    path('deer_wait_list/', include('deer_wait_list.urls')),
    path('admin_toolbox/', include('admin_toolbox.urls')),
    path('status_watcher/', include('status_watcher.urls')),
    path('content_collection/', include('content_collection.urls')),
    path('call_of_the_wild/', include('call_of_the_wild.urls')),
    path('shooting_challenge/', include('shooting_challenge.urls')),
    path('dcsa_info/', include('dcsa_info.urls')),
    path('bingo/', include('bingo.urls')),
    path('puppy_fostering/', include('puppy_fostering.urls')),
    path('meme_leach/', include('meme_leach.urls')),


    # path('contact/', views.contact, name='contact'),
    # path('about/', views.about, name='about'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('login/',
         LoginView.as_view
             (
             template_name='imrunicorn/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Log In',
                 'copy_year': datetime.now().year,
                 'release': get_version_json(),
                 'blurb': 'I am not allowing new accounts at this time.',
                 'no_accounts_blurb': 'If you have an account and need a reset, you know how to reach me..',
             }
         ),
         name='login'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# # https://docs.djangoproject.com/en/2.0/topics/http/views/#customizing-error-views
# handler404 = 'YOUR_APP_NAME.views.handler404'

handler404 = 'imrunicorn.views.handler404'
handler403 = 'imrunicorn.views.handler403'
handler500 = 'imrunicorn.views.handler500'

imrunicorn/content_collection/views.py
import urllib
from rest_framework.response import Response
from rest_framework import viewsets, generics, status
from rest_framework.decorators import api_view, permission_classes
from django.http import JsonResponse
import requests
from django.contrib.auth.decorators import permission_required
from django.http import HttpResponse
from django.shortcuts import render
from rest_framework.parsers import JSONParser

from announcements.get_news import get_news, get_news_sticky, get_news_by_pk, get_version_json, \
    get_page_blurb_override, get_restart_notice
from imrunicorn.functions import step_hit_count_by_page
from datetime import datetime
from content_collection.functions import get_all_videos, get_latest_video, get_video_by_pk, \
    get_recent_pictures_for_carousel, get_all_pictures_for_carousel, get_all_dnd5e, \
    get_all_fantasy_grounds, get_all_insults, get_all_secrets, get_all_buzz_words_or_phrases, get_sketch_by_pk, \
    get_all_sketches

# from django.contrib.auth import get_user_model
from django.shortcuts import render
from imrunicorn.decorators import allowed_groups
# @allowed_groups(allowed_groupname_list=['admin_tools_members'])
# request.user.groups.filter(name__in=allowed_groupname_list).exists()
from .models import SensorReadings
from .serializer import RandomInsultSerializer, SensorReadingsSerializer


def buzz_words_or_phrases_list_all(request):
    step_hit_count_by_page(request.path)
    words = get_all_buzz_words_or_phrases()

    new_entries = words['new_entries']

    word_list = words['result']
    context = {
        "copy_year": datetime.now().year,
        'release': get_version_json(),
        "title": "Content Collection: Buzz Words (or Phrases)",
        "words": word_list,
        "new_words_or_phrases": new_entries,
        "blurb": get_page_blurb_override('content_collection/buzz_words_or_phrases_list_all/'),
    }
    return render(request, "content_collection/buzz_words_or_phrases_list_all.html", context)


@permission_required('content_collection.view_secrets', login_url='/login', raise_exception=True)
def secrets_list_all(request):
    step_hit_count_by_page(request.path)
    secrets = get_all_secrets

    context = {
        "copy_year": datetime.now().year,
        'release': get_version_json(),
        "title": "Content Collection: Secrets",
        "secrets": secrets,
        "blurb": get_page_blurb_override('content_collection/secrets_list_all/'),
    }
    return render(request, "content_collection/secrets_list_all.html", context)


def insult_list_all(request):
    # return HttpResponse("hello world")

    # get the list of todos
    # response = requests.get('https://jsonplaceholder.typicode.com/todos/')
    # transfer the response to json objects
    # todos = response.json()   # send todos in context... BAM

    step_hit_count_by_page(request.path)
    insults = get_all_insults

    context = {
        "copy_year": datetime.now().year,
        'release': get_version_json(),
        "title": "Content Collection: Insult",
        "insults": insults,
        "blurb": get_page_blurb_override('content_collection/insult/'),
    }
    return render(request, "content_collection/insult_list_all.html", context)


# todo: make a buzzword generator!
# https://www.robietherobot.com/buzzword.htm

def leach_insult(request):
    step_hit_count_by_page(request.path)
    insult_one = "I failed to get data."
    insult_two = "I failed to get data."
    try:
        url = "https://www.kassoon.com/dnd/vicious-mockery-insult-generator/"
        page = urllib.request.urlopen(url)
        content = page.read().decode()
        content_parts = content.split("</p><p>OR</p><p>")

        # get insult one
        core_part_one = content_parts[0]
        insult_one = core_part_one[core_part_one.rindex('<p>')+4:]

        # get the second insult on the page
        core_part_two = content_parts[1]
        core_part_two_bits = core_part_two.split("</p>")
        insult_two = core_part_two_bits[0]

    except Exception as ex:
        print("Exception: {0}".format(ex))

    # save the insults
    saved_insult_count = 0

    # save the first insult
    insult = {'insult': insult_one}
    status_code_message = ""
    try:
        insult_serializer = RandomInsultSerializer(data=insult)
        if insult_serializer.is_valid():
            insult_serializer.save()
            status_code_message = "Saved newly generated insult to database."
            saved_insult_count += 1
    except Exception as ex:
        print(ex)

    # save the second insult
    insult = {'insult': insult_two}
    status_code_message = ""
    try:
        insult_serializer = RandomInsultSerializer(data=insult)
        if insult_serializer.is_valid():
            insult_serializer.save()
            status_code_message = "Saved newly generated insult to database."
            saved_insult_count += 1
    except Exception as ex:
        print(ex)

    # insult = [insult_one, insult_two]
    if saved_insult_count == 0:
        status_code_message = ""
    elif saved_insult_count == 1:
        status_code_message = "Saved newly generated insult to database."
    elif saved_insult_count == 2:
        status_code_message = "Saved two newly generated insults to database."
    else:
        status_code_message = "Something went terribly wrong."

    insults = [insult_one, insult_two]

    context = {
        "copy_year": datetime.now().year,
        'release': get_version_json(),
        "title": "Content Collection: Insult",
        "insults": insults,
        "status_code_message": status_code_message,
        "blurb": get_page_blurb_override('content_collection/insult/'),
    }
    return render(request, "content_collection/insult.html", context)


def page_home(request):
    step_hit_count_by_page(request.path)
    context = {
        "copy_year": datetime.now().year,
        'release': get_version_json(),
        "title": "Content Collection: Home",
        "blurb": get_page_blurb_override('content_collection/home/'),
    }
    return render(request, "content_collection/home.html", context)


# Create your views here.
def page_blank(request):
    step_hit_count_by_page(request.path)
    context = {
        "copy_year": datetime.now().year,
        'release': get_version_json(),
        "title": "Content Collection: Blank",
        "blurb": get_page_blurb_override('content_collection/blank/'),
    }
    return render(request, "content_collection/blank.html", context)


# @allowed_groups(allowed_groupname_list=['content_collection_fantasy_grounds'])
# @permission_required('content_collection.view_fantasygrounds', login_url='/login', raise_exception=True)
def page_fantasy_grounds_list(request):
    step_hit_count_by_page(request.path)
    item_list = get_all_fantasy_grounds()

    perm_check = request.user.has_perm('content_collection.view_fantasygrounds')
    unrestricted = perm_check

    context = {
        "copy_year": datetime.now().year,
        'release': get_version_json(),
        "title": "Fantasy Grounds",
        "item_list": item_list,
        "blurb": get_page_blurb_override('content_collection/dnd5e/'),
    }
    return render(request, "content_collection/dnd5e.html", context)


# @allowed_groups(allowed_groupname_list=['content_collection_dnd5e'])
@permission_required('content_collection.view_danddfiftheditionbook', login_url='/login', raise_exception=True)
def page_dnd5e_list(request):
    step_hit_count_by_page(request.path)
    item_list = get_all_dnd5e()

    perm_check = request.user.has_perm('content_collection.view_danddfiftheditionbook')
    unrestricted = perm_check

    context = {
        "copy_year": datetime.now().year,
        'release': get_version_json(),
        "title": "D&D-5e",
        "item_list": item_list,
        "unrestricted_user": unrestricted,
        "blurb": get_page_blurb_override('content_collection/dnd5e/'),
    }
    return render(request, "content_collection/dnd5e.html", context)


# @permission_required('content_collection.view_PicturesForCarousel', login_url='/login', raise_exception=True)
def page_carousel_recent(request):
    step_hit_count_by_page(request.path)
    carousel = get_recent_pictures_for_carousel()

    perm_check = request.user.has_perm('content_collection.view_picturesforcarousel')
    unrestricted = perm_check

    context = {
        "copy_year": datetime.now().year,
        'release': get_version_json(),
        "title": "Carousel: Recent",
        'unrestricted_user': unrestricted,
        "carousel": carousel,
        "blurb": get_page_blurb_override('content_collection/carousel/recent/'),
    }
    return render(request, "content_collection/carousel.html", context)


# @permission_required('content_collection.view_PicturesForCarousel', login_url='/login', raise_exception=True)
def page_carousel(request):
    step_hit_count_by_page(request.path)
    carousel = get_all_pictures_for_carousel()

    perm_check = request.user.has_perm('content_collection.view_picturesforcarousel')
    unrestricted = perm_check

    context = {
        "copy_year": datetime.now().year,
        'release': get_version_json(),
        "title": "Carousel (All)",
        'unrestricted_user': unrestricted,
        "carousel": carousel,
        "blurb": get_page_blurb_override('content_collection/carousel/'),
    }
    return render(request, "content_collection/carousel.html", context)


# @permission_required('content_collection.view_Video', login_url='/login', raise_exception=True)
def page_latest_video_by_pk(request, video_pk=1):
    step_hit_count_by_page(request.path)
    videos = get_video_by_pk(video_pk)

    perm_check = request.user.has_perm('content_collection.view_video')
    unrestricted = perm_check

    context = {
        "videos": videos,
        "copy_year": datetime.now().year,
        'release': get_version_json(),
        'unrestricted_user': unrestricted,
        "title": "Videos: #{video_id}".format(video_id=video_pk),

imrunicorn/content_collection/templates/content_collection/blank.html
{% extends "imrunicorn/layout.html" %}

{% block extra_head %}

{% endblock %}



{% block content %}
<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">{% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            The robot that lives at this website is AFK and hasn't picked a page blurb yet.
        {% endif %}</p>
</div>

<div class="row ben_format_pretty">
    This page is blank, mostly.
</div>

{% endblock %}

imrunicorn/content_collection/templates/content_collection/buzz_words_or_phrases_list_all.html
{% extends "imrunicorn/layout.html" %}

{% block extra_head %}

{% endblock %}



{% block content %}
<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">{% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            This might take a bit to load, thank you for your patience.
        {% endif %}</p>
</div>


<div class="row ben_format_pretty">
        <div align="center">
        <div>
            {% include 'content_collection/chart_menu.html' %}
        </div>
    </div>
</div>
<br />


<div class="row ben_format_pretty">
    Not to worry, there are more buzz words coming for management reasons.

    {% if new_words_or_phrases > 0 %}
        We were able to find {{ new_words_or_phrases }} more
            {% if new_words_or_phrases > 1 %}
                buzzwords
            {% else %}
                buzzword
            {% endif %}
        just now, so the list has been updated to reflect that.
    {% endif %}
    <br /><br /><br />

    {% for word in words %}

        <strong>{{ word.pk }}:</strong> {{ word.word_or_phrase }}<br />

        {% if forloop.last  == True %}
            <br />
        {% endif %}

    {% endfor %}
</div>

{% endblock %}

imrunicorn/content_collection/templates/content_collection/carousel-sample-lkg.html
{% extends "imrunicorn/layout.html" %}

{% block extra_head %}

{% endblock %}



{% block content %}
<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">{% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            The robot that lives at this website is AFK and hasn't picked a page blurb yet.
        {% endif %}</p>
</div>

<div class="row ben_format_pretty">
    Carousel pictures, are not restricted here.<br /><br />

    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">

                {% for item in carousel %}
                    {% if forloop.first %}
                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    {% else %}
                        <li data-target="#carousel-example-generic" data-slide-to="{{forloop.counter}}"></li>
                    {% endif %}
                {% endfor %}
            </ol>
            <div class="carousel-inner">

                {% for item in carousel %}
                    {% if forloop.first %}
                        <div class="item active">
                            {% if item.picture.url != None %}
                                <img class="slide-image" src="{{ item.picture.url }}" alt="{{ item.caption }}">
                            {% else %}
                                {% if item.link_to_external|first in 'http' %}
                                    <img class="slide-image" src="{{ item.link_to_external }}" alt="{{ item.caption }}">
                                {% else %}
                                    <img class="slide-image" src="{{request.scheme}}://{{request.get_host}}{{ item.link_to_external }}" alt="{{ item.caption }}">
                                {% endif %}
                            {% endif %}
                        </div>
                    {% else %}
                        <div class="item">
                            {% if item.picture.url != None %}
                                <img class="slide-image" src="{{ item.picture.url }}" alt="{{ item.caption }}">
                            {% else %}
                                {% if item.link_to_external|first in 'http' %}
                                    <img class="slide-image" src="{{ item.link_to_external }}" alt="{{ item.caption }}">
                                {% else %}
                                    <img class="slide-image" src="{{request.scheme}}://{{request.get_host}}{{ item.link_to_external }}" alt="{{ item.caption }}">
                                {% endif %}
                            {% endif %}
                        </div>
                    {% endif %}
                {% endfor %}


            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>

        </div>
    </div>






</div>

{% endblock %}

imrunicorn/content_collection/templates/content_collection/chart_menu.html
<a class="dropdown-item" href="{% url 'content_collection:video_list' %}"> Video List</a> |
<a class="dropdown-item" href="{% url 'content_collection:videos_latest' %}"> Video Latest</a> |
<a class="dropdown-item" href="{% url 'content_collection:carousel' %}"> Carousel</a> |
<a class="dropdown-item" href="{% url 'content_collection:carousel_recent' %}"> Carousel Recent</a> |
<a class="dropdown-item" href="{% url 'content_collection:dnd5e_list' %}"> D&amp;D 5e</a> |
<a class="dropdown-item" href="{% url 'content_collection:fantasy_grounds_list' %}"> Fantasy Grounds</a> |
<a class="dropdown-item" href="{% url 'content_collection:insult' %}"> Insult</a> |
<a class="dropdown-item" href="{% url 'content_collection:secrets_list_all' %}"> Secrets</a> |
<a class="dropdown-item" href="{% url 'content_collection:buzz_words_or_phrases_list_all' %}"> Buzz Words</a> |
<a class="dropdown-item" href="{% url 'content_collection:sketches' %}"> Sketches</a>

imrunicorn/content_collection/templates/content_collection/dnd5e.html
{% extends "imrunicorn/layout.html" %}

{% block extra_head %}

{% endblock %}



{% block content %}
<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">{% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            The robot that lives at this website is AFK and hasn't picked a page blurb yet.
        {% endif %}</p>
</div>


<div class="row ben_format_pretty">
        <div align="center">
        <div>
            {% include 'content_collection/chart_menu.html' %}
        </div>
    </div>
</div>
<br />


<div class="row ben_format_pretty">
    List of Dungeons &amp; Dragons (5th Edition) books, some may be hidden because of access.

    <br /><br />
        <ul>
        {% for item in item_list %}

            {% comment %}
            <li><a href="{{ item.file_name.url }}" target="_blank">#{{ item.pk }} - {{ item.file_title}}</a></li>
            {% endcomment %}

            {% if item.restricted %}
                {% if unrestricted_user %}
                    <li><a href="{{ item.file_name.url }}" target="_blank">#{{ item.pk }} - {{ item.file_title}}</a></li>
                {% endif %}
            {% else %}
                <li><a href="{{ item.file_name.url }}" target="_blank">#{{ item.pk }} - {{ item.file_title}}</a></li>
            {% endif %}


        {% endfor %}
        </ul>

</div>

{% endblock %}

imrunicorn/content_collection/templates/content_collection/insult.html
{% extends "imrunicorn/layout.html" %}

{% block extra_head %}

{% endblock %}



{% block content %}
<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">{% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            The robot that lives at this website is AFK and hasn't picked a page blurb yet.
        {% endif %}</p>
</div>


<div class="row ben_format_pretty">
        <div align="center">
        <div>
            {% include 'content_collection/chart_menu.html' %}
        </div>
    </div>
</div>
<br />


<div class="row ben_format_pretty">

    {% for item in insults %}
        <strong>{{ item }}</strong>
        {% if forloop.last  == False %}
            <br /><i>OR</i><br />
        {% else %}
            <br /><br />
            View the <a href="{% url 'content_collection:insult_list_all' %}">insult list</a><br />
            View the <a href="/api/content_collection/insults/" target="_blank">insult list</a> (API LIST)<br />
        {% endif %}
    {% endfor %}


    {% if status_code_message|length > 0 %}
        <br /><br /><i>{{ status_code_message }}</i>
    {% endif %}
</div>

{% endblock %}

imrunicorn/content_collection/templates/content_collection/sketches_list.html
{% extends "imrunicorn/layout.html" %}

{% block extra_head %}

{% endblock %}



{% block content %}
<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">{% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            The robot that lives at this website is AFK and hasn't picked a page blurb yet.
        {% endif %}</p>
</div>


<div class="row ben_format_pretty">
        <div align="center">
        <div>
            {% include 'content_collection/chart_menu.html' %}
        </div>
    </div>
</div>
<br />


<div class="row ben_format_pretty">
    <br /><br />
        <ul>
        {% for item in sketches %}
            {% if item.restricted %}
                {% if unrestricted_user %}
                    <li><a href="{% url 'content_collection:sketches' %}{{ item.pk }}">#{{ item.pk }} - {{ item.title }}</a>
                {% else %}
                    <li><a href="{% url 'content_collection:sketches' %}{{ item.pk }}">#{{ item.pk }} - [ Access denied, title hidden ]</a>
                {% endif %}
            {% else %}
                <li><a href="{% url 'content_collection:sketches' %}{{ item.pk }}">#{{ item.pk }} - {{ item.title}}</a>
            {% endif %}
                </li>
        {% endfor %}
        </ul>

</div>

{% endblock %}

imrunicorn/content_collection/templates/content_collection/video_list.html
{% extends "imrunicorn/layout.html" %}

{% block extra_head %}

{% endblock %}



{% block content %}
<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">{% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            The robot that lives at this website is AFK and hasn't picked a page blurb yet.
        {% endif %}</p>
</div>


<div class="row ben_format_pretty">
        <div align="center">
        <div>
            {% include 'content_collection/chart_menu.html' %}
        </div>
    </div>
</div>
<br />


<div class="row ben_format_pretty">
    List of videos, some may be hidden because of access.

    <br /><br />
        <ul>
        {% for item in videos %}
            {% if item.restricted %}
                {% if unrestricted_user %}
                    <li><a href="{% url 'content_collection:video_list' %}{{ item.pk }}">#{{ item.pk }} - {{ item.file_title }}</a>
                {% else %}
                    <li><a href="{% url 'content_collection:video_list' %}{{ item.pk }}">#{{ item.pk }} - [ Title Hidden ]</a>
                {% endif %}
            {% else %}
                <li><a href="{% url 'content_collection:video_list' %}{{ item.pk }}">#{{ item.pk }} - {{ item.file_title}}</a>
            {% endif %}
                </li>
        {% endfor %}
        </ul>

</div>

{% endblock %}