imrunicorn/api/urls.py
from django.urls import path, include
from . import views
from content_collection import views as c_views
# from meme_leach import views as meme_leach_views
from rest_framework import routers
from django.views.generic import TemplateView
# from api.views import ChartData as GroundHogChartData
from groundhog_logbook.views import ChartDataBySex
# from api.views import ChartDataTest
from .views import ActivityLogViewSet

# similar to object based url building
router = routers.DefaultRouter()
# router.get_api_root_view().cls.__name__ = "BenSpelledABC: API"
# router.get_api_root_view().cls.__doc__ = "Becoming the backbone to wonderland."

router.register('activity_log/activity', views.ActivityViewSet)
router.register('activity_log/activity_log', views.ActivityLogViewSet)
router.register('activity_log/activity_photo_validation', views.ActivityPhotoValidationViewSet)

router.register('announcements/what_is_new', views.WhatIsNewView)
router.register('announcements/main_page_blurbs', views.MainPageBlurbsView)
router.register('announcements/page_blurb_overrides', views.PageBlurbOverridesView)

router.register('content_collection/insults', views.ContentCollectionInsultsViewSet)

router.register('deer_wait_list/Recipient', views.DeerWaitListRecipient)
router.register('deer_wait_list/MeatCut', views.DeerWaitListMeatCut)
router.register('deer_wait_list/Flavor', views.DeerWaitListFlavor)
router.register('deer_wait_list/RequestedOrder', views.DeerWaitListRequestedOrder)

router.register('loaddata/Owner', views.Owner)
router.register('loaddata/Caliber', views.LoadDataCaliber)
router.register('loaddata/Firearm', views.LoadDataFirearm)
router.register('loaddata/Powder', views.LoadDataPowder)
router.register('loaddata/Projectile', views.LoadDataProjectile)
router.register('loaddata/Brass', views.LoadDataBrass)
router.register('loaddata/Primer', views.LoadDataPrimer)
router.register('loaddata/HandLoad', views.LoadDataHandLoad)
router.register('loaddata/EstimatedDope', views.LoadDataEstimatedDope)

router.register('groundhog_logbook/Location', views.LocationView)
router.register('groundhog_logbook/RemovalsByLocation', views.RemovalsByLocationView)
# router.register('groundhog_logbook/chart/data/test', ChartDataTest.as_view(), basename=ChartDataTest)

router.register('deer_harvest_logbook/Harvests', views.HarvestsView)
router.register('deer_harvest_logbook/HarvestsPhotos', views.HarvestsPhotosView)

router.register('shooting_challenge/ChallengeEvent', views.ChallengeEventViewSet)
router.register('shooting_challenge/ChallengePhoto', views.ChallengePhotoViewSet)

router.register('accounts', views.Accounts)

router.register('meme_leach', views.MemeLeachViewSet)
# router.register('meme_leach/<str:subreddit>', views.MemeLeachViewSet.random_meme_by_subreddit_name)

# router.register('sensor_reading', c_views.sensor_readings)

# /api/docker/hook
# router.register('docker_hub_hook', views.docker_hub_webhook)


# HyperlinkedModelSerializer doesn't like namespace addressing for the 'url' to work
# app_name = 'api'
urlpatterns = [
    # path('DeerWaitListRecipient/', views.DeerWaitListRecipient, name='DeerWaitListRecipient'),
    # path("activity_log", ActivityLogViewSet.as_view(), name='activity_log'),
    path('', include(router.urls)),
    path('docker_hub_hook/', views.docker_hub_webhook, name='docker_hub_webhook'),
    path('sensor_reading/', c_views.sensor_readings, name='sensor_readings'),

    path('meme_leach/<str:subreddit>', views.random_meme_by_subreddit),
]

imrunicorn/groundhog_logbook/urls.py
from django.urls import path, include
from . import views
from .views import ChartDataBySex, ChartDataByTime, ChartDataByMonth, ChartDataByCloudLevel, ChartDataByTemperature, \
    ChartDataByRemover, ChartDataByYear, ChartDataByCaliber, ChartDataByDistance
# from api.views import ChartData as GroundHogChartData


app_name = 'groundhog_logbook'
urlpatterns = [
    path('by_shooter/', views.page_all_groundhog_removals, name='all_groundhog_removals'),
    path('by_shooter/<int:shooter_pk>', views.page_all_groundhog_removals_by_shooter_pk, name='all_groundhog_removals'),

    path('', views.page_all_groundhog_removals, name='all_groundhog_removals_base'),
    path('locations/', views.page_all_groundhog_locations, name='all_groundhog_locations'),
    path('charts/', views.page_charts, name='page_charts'),
    path('removal_scoreboard/', views.page_groundhog_removals_scoreboard, name='groundhog_removal_scoreboard'),
    path('removal_scoreboard_annual/', views.page_groundhog_removals_scoreboard_annual,
         name='groundhog_removal_scoreboard_annual'),

    # charts by sex
    path('charts/by_sex/', views.page_charts_by_sex, name='charts_by_sex'),
    path('api/chart/by_sex/data/', ChartDataBySex.as_view()),

    path('charts/by_time/', views.page_charts_by_time, name='charts_by_time'),
    path('api/chart/by_time/data/', ChartDataByTime.as_view()),

    path('charts/by_month/', views.page_charts_by_month, name='charts_by_month'),
    path('api/chart/by_month/data/', ChartDataByMonth.as_view()),

    path('charts/by_year/', views.page_charts_by_year, name='charts_by_year'),
    path('api/chart/by_year/data/', ChartDataByYear.as_view()),

    path('charts/by_cloud_level/', views.page_charts_by_cloud_level, name='charts_by_cloud_level'),
    path('api/chart/by_cloud_level/data/', ChartDataByCloudLevel.as_view()),

    path('charts/by_temperature/', views.page_charts_by_temperature, name='charts_by_temperature'),
    path('api/chart/by_temperature/data/', ChartDataByTemperature.as_view()),

    path('charts/by_remover/', views.page_charts_by_remover, name='charts_by_remover'),
    path('api/chart/by_remover/data/', ChartDataByRemover.as_view()),

    path('charts/by_caliber/', views.page_charts_by_caliber, name='charts_by_caliber'),
    path('api/chart/by_caliber/data/', ChartDataByCaliber.as_view()),

    path('charts/by_distance/', views.page_charts_by_distance, name='charts_by_distance'),
    path('api/chart/by_distance/data/', ChartDataByDistance.as_view()),

]

imrunicorn/imrunicorn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from datetime import datetime
from django.conf import settings
# from . import forms, views
from announcements.get_news import get_news, get_version_json
from django.conf import settings
from django.conf.urls.static import static
from . import forms, views


# app_name = 'base_skipped_for_now'
urlpatterns = [

    path('test/', views.page_test_layout, name='test_layout'),

    path('api-auth/', include('rest_framework.urls')),
    path('api/weather/', views.page_api_weather, name='page_api_weather'),
    path('qr/about/', views.page_qr_about, name='qr_about'),
    path('admin/', admin.site.urls),
    path('', views.page_home, name='home'),

    path('access_denied_groups', views.page_access_denied_groups, name='access_denied_groups'),

    path('page_hits/', views.page_page_hits, name='page_hits'),

    path('activity_log/', include('activity_log.urls')),
    path('announcements/', include('announcements.urls')),
    path('api/', include('api.urls')),
    path('load_data/', include('loaddata.urls')),
    # path('farm_invite/', include('farminvite.urls')),
    path('polls/', include('polls.urls')),
    path('shooting_logbook/', include('shooting_logbook.urls')),
    path('groundhog_logbook/', include('groundhog_logbook.urls')),
    path('deer_harvest_logbook/', include('deer_harvest_logbook.urls')),
    path('deer_wait_list/', include('deer_wait_list.urls')),
    path('admin_toolbox/', include('admin_toolbox.urls')),
    path('status_watcher/', include('status_watcher.urls')),
    path('content_collection/', include('content_collection.urls')),
    path('call_of_the_wild/', include('call_of_the_wild.urls')),
    path('shooting_challenge/', include('shooting_challenge.urls')),
    path('dcsa_info/', include('dcsa_info.urls')),
    path('bingo/', include('bingo.urls')),
    path('puppy_fostering/', include('puppy_fostering.urls')),
    path('meme_leach/', include('meme_leach.urls')),


    # path('contact/', views.contact, name='contact'),
    # path('about/', views.about, name='about'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('login/',
         LoginView.as_view
             (
             template_name='imrunicorn/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Log In',
                 'copy_year': datetime.now().year,
                 'release': get_version_json(),
                 'blurb': 'I am not allowing new accounts at this time.',
                 'no_accounts_blurb': 'If you have an account and need a reset, you know how to reach me..',
             }
         ),
         name='login'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# # https://docs.djangoproject.com/en/2.0/topics/http/views/#customizing-error-views
# handler404 = 'YOUR_APP_NAME.views.handler404'

handler404 = 'imrunicorn.views.handler404'
handler403 = 'imrunicorn.views.handler403'
handler500 = 'imrunicorn.views.handler500'

imrunicorn/loaddata/urls.py
from django.urls import path
from . import views

# router = routers.DefaultRouter()
# router.register('roll', views.RollView)
# router.register('student', views.StudentView)
# router.register('courses', views.CourseView)

app_name = 'load_data'
urlpatterns = [
    path('', views.page_loads, name='home'),

    path('foot_pound_calculator/', views.page_foot_pound_calc, name='foot_pound_calculator'),

    # page_loads_details
    path('loads/', views.page_loads, name='loads'),
    path('loads/<int:load_pk>', views.page_loads_details, name='loads'),
    path('loads/<str:load_type>', views.page_loads_by_type, name='loads'),

    path('estimated_dope/<int:load_pk>', views.page_estimated_dope, name='page_estimated_dope'),
    path('estimated_dope/', views.page_estimated_dope, name='page_estimated_dope'),

    path('firearm_detail/<int:firearm_pk>', views.page_firearm_detail, name='page_firearm_detail'),
    path('firearm_detail/', views.page_firearm_detail, name='page_firearm_detail'),

    path('caliber_detail/<int:caliber_pk>', views.page_caliber_detail, name='page_caliber_detail'),
    path('caliber_detail/', views.page_caliber_detail, name='page_caliber_detail'),

    path('toolbox/', views.home_create_view, name='create_home'),
    path('toolbox/create_caliber/', views.caliber_create_view, name='create_caliber'),
    path('toolbox/create_powder/', views.powder_create_view, name='create_powder'),
    path('toolbox/create_projectile/', views.projectile_create_view, name='create_projectile'),
    path('toolbox/create_firearm/', views.firearm_create_view, name='create_firearm'),

    path('docker/', views.docker_update_test, name='docker_update_test'),

]

imrunicorn/groundhog_logbook/models.py
from datetime import date
from django.db import models
from loaddata.models import Firearm, HandLoad
from decimal import Decimal
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from imrunicorn.functions import get_weather


class Location(models.Model):
    nickname = models.CharField(max_length=150, default=None, blank=True, null=True)
    # https://viewer.nationalmap.gov/theme/elevation/
    elevation = models.DecimalField(max_digits=5, decimal_places=0, default=764, null=True)
    latitude = models.DecimalField(max_digits=12, decimal_places=7, default=39.575230, null=True)
    longitude = models.DecimalField(max_digits=12, decimal_places=7, default=-76.996040, null=True)
    hole_location_picture = models.ImageField(upload_to='uploads/groundhog_hole_locations/', null=True, blank=True)

    def get_lat(self):
        return self.latitude

    def get_long(self):
        return self.longitude

    def __str__(self):
        return "%s (%s LAT , %s LONG)" % (self.nickname, self.latitude, self.longitude)

    class Meta:
        ordering = ('nickname', 'latitude', 'longitude')


class RemovalPhoto(models.Model):
    kill_shot = models.ImageField(upload_to='uploads/groundhog_kill_shots/', null=True, blank=True)
    photo_date = models.DateField(default=date.today)

    def __str__(self):
        return "%s - %s - %s" % (self.id, self.photo_date, self.kill_shot.url)

    class Meta:
        ordering = ('-photo_date', '-id')


class RemovalsByLocation(models.Model):
    shooter = models.ForeignKey(User, related_name='groundhog_logbook_shooter', on_delete=models.CASCADE, null=True)
    removal_date = models.DateField(default=date.today)
    removal_time = models.TimeField(null=True)
    estimated_temperature = models.IntegerField(
        null=True,
        default=-49,
        validators=[
            MaxValueValidator(120),
            MinValueValidator(-50)
        ]
     )

    CLEAR_SKY = 'Clear Sky'
    FEW_CLOUDS = 'Few Clouds'
    SCATTERED_CLOUDS = 'Scattered Clouds'
    BROKEN_CLOUDS = 'Broken Clouds'
    SHOWER_RAIN = "Shower/Rain"
    RAIN = "Rain"
    THUNDERSTORM = "Thunderstorm"
    SNOW = "Snow"
    MIST = "Mist"
    UNKNOWN = 'Unknown'

    cloud_level_choices = [
        (CLEAR_SKY, 'Clear Sky'),
        (FEW_CLOUDS, 'Few Clouds'),
        (SCATTERED_CLOUDS, 'Scattered Clouds'),
        (BROKEN_CLOUDS, 'Broken Clouds'),
        (SHOWER_RAIN, 'Shower/Rain'),
        (RAIN, 'Rain'),
        (THUNDERSTORM, 'Thunderstorm'),
        (SNOW, 'Snow'),
        (MIST, 'Mist'),
        (UNKNOWN, 'Unknown'),
    ]
    cloud_level = models.CharField(
        max_length=20,
        choices=cloud_level_choices,
        default=UNKNOWN,
    )
    wind_speed = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    wind_dir = models.IntegerField(default=-1)
    wind_dir_word = models.CharField(max_length=40, null=True, blank=True)
    weather_icon_url = models.CharField(max_length=400, null=True, blank=True)
    firearm = models.ForeignKey(Firearm, related_name='groundhog_logbook_firearm', on_delete=models.CASCADE)
    load = models.ForeignKey(HandLoad, related_name='groundhog_logbook_hand_load', on_delete=models.CASCADE)
    location = models.ForeignKey(Location, related_name='location', on_delete=models.CASCADE)
    estimated_weight_lbs = models.DecimalField(max_digits=4, decimal_places=2, default=10.25)
    excessive_wound_cavity = models.BooleanField(default=False)
    foot_hold_trapped = models.BooleanField(default=False)
    shot_distance_yards = models.DecimalField(max_digits=4, decimal_places=0, default=200)
    yards_ran = models.DecimalField(max_digits=4, decimal_places=1, default=0)
    extra_info = models.TextField(blank=True, null=True)  # i like big comments...
    # upload the kill shot!?
    kill_shot = models.ImageField(upload_to='uploads/groundhog_kill_shots/', null=True, blank=True)
    kill_shot_two = models.ImageField(upload_to='uploads/groundhog_kill_shots/', null=True, blank=True)

    removal_photos = models.ManyToManyField(RemovalPhoto, blank=True)

    UNKNOWN = 'UNKNOWN'
    MALE = 'MALE'
    FEMALE = 'FEMALE'

    SEX_CHOICES = [
        (UNKNOWN, 'Unknown'),
        (MALE, 'Male'),
        (FEMALE, 'Female'),
    ]
    sex = models.CharField(
        max_length=20,
        choices=SEX_CHOICES,
        default=UNKNOWN,
    )

    def save(self, *args, **kwargs):
        if self.wind_speed == 0.00 and self.wind_dir == -1 and self.estimated_temperature == -49:
            # only fetch weather if it appears to be defaults
            # weather = get_weather(self)
            weather = get_weather(self, self.location.latitude, self.location.longitude)
            self.estimated_temperature = weather['temperature']
            self.cloud_level = weather['description']
            self.wind_speed = weather['wind_speed']
            self.wind_dir = weather['wind_dir']
            self.wind_dir_word = weather['wind_dir_word']
            self.weather_icon_url = weather['weather_icon_url']
        super(RemovalsByLocation, self).save(*args, **kwargs)

    def __str__(self):
        name = self.shooter
        try:
            name = self.shooter.userprofile.preferred_display_name
        except Exception as e:
            name = self.shooter
        return "%s - %s (%s yards from '%s')" % (self.removal_date,
                                                 name,
                                                 self.shot_distance_yards,
                                                 self.location.nickname)

    class Meta:
        # shooter__userprofile__preferred_display_name
        ordering = ('-removal_date', 'shooter', 'shot_distance_yards')

imrunicorn/groundhog_logbook/templates/groundhog_logbook/all_groundhog_hole_locations.html
{% extends "imrunicorn/layout.html" %}

{% block extra_head %}

{% endblock %}


{% block content %}
{% load humanize %}

<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">{% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            The robot that lives at this website is AFK and hasn't picked a page blurb yet.
        {% endif %}</p>
</div>


{% if list_of_holes != None %}

<div class="row ben_format_pretty">
    <div class='post-body entry-content' id='post-body-3156955225064661913' itemprop='description articleBody'>
        <div style="text-align: left;font-family:times new roman;">
            These could be a few feet off so look around a little bit.<br /><br />
            <strong>
                <a href="https://www.google.com/maps/d/edit?mid=1oKonLT_hz3f0q0_tMRIxC7GcoOjll455&ll=39.619590204745705%2C-77.02708839986629&z=17"
                   target="_blank">
                    View All On GoogleMaps</a></strong><br /><br />

            <!-- https://www.google.com/maps/search/?api=1&query=<lat>,<lng> -->
            <!-- https://www.google.com/maps/search/?api=1&query=39.619507,-77.029337 -->

            {% for item in list_of_holes %}
          
                <b>Location: </b>{{ item.nickname | title }}<br />
                <a href="https://www.google.com/maps/search/?api=1&query={{ item.latitude }},{{ item.longitude }}"
                                   target="_blank">{{ item.nickname | title }} - ({{ item.latitude }},{{ item.longitude }})</a><br />
                {% if item.hole_location_picture %}
                    Hole Picture:<br />
                    <a href="{{ item.hole_location_picture.url }}" target="_blank">
                        <img src="{{ item.hole_location_picture.url }}" style="width: 30%" /></a><br />
                {% endif %}
                <br />


            {% if forloop.last  == False %}
                <hr style="height:2px;border-width:0;color:gray;background-color:red" />
            {% else %}
                <br />
            {% endif %}


            {% endfor %}
        </div>

    </div>
</div>
{% else %}
<div class="row ben_format_pretty">
    <div class='post-body entry-content' id='post-body-3156955225064661913' itemprop='description articleBody'>
        <div style="text-align: left;font-family:times new roman;">
            It appears we haven't started to track holes!
        </div>

    </div>
</div>
{% endif %}


{% endblock %}

imrunicorn/groundhog_logbook/templates/groundhog_logbook/groundhog_graphic_generic.html
{% extends "imrunicorn/layout.html" %}

<script>
{% block jquery %}
var endpoint = '{{ graph_api_node }}'
var defaultData = []
var labels = [];
$.ajax({
    method: "GET",
    url: endpoint,

    success: function(data){
        console.log(data)
        labels = data.labels
        defaultData = data.default
        setChart()
    },
    error: function(error_data){
        console.log("error")
        console.log(error_data)
    }
})

function setChart(){
    var ctx = document.getElementById("myChart");
    var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: labels,
        datasets: [{
            label: '{{ graph_header }}',
            data: defaultData,

            backgroundColor: [
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)',
                'rgba(200, 0, 0, 1)'
            ],
            borderColor: [
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)',
                'rgba(160,160,160,1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});

}

{% endblock %}
</script>

{% block content %}

<div class="jumbotron wallpapered">
    <h1>{{ title }}</h1>
    <p class="lead">
            {% if blurb|length > 0 %}
            {{ blurb }}
        {% else %}
            The robot that lives at this website is AFK and hasn't picked a page blurb yet.
        {% endif %}
    </p>
</div>

<div class="row ben_format_pretty">
        <div align="center">
        <div>
            <a class="dropdown-item" href="{% url 'groundhog_logbook:charts_by_sex' %}"> By Sex</a> |
            <a class="dropdown-item" href="{% url 'groundhog_logbook:charts_by_time' %}"> By Time</a> |
            <a class="dropdown-item" href="{% url 'groundhog_logbook:charts_by_month' %}"> By Month</a> |
            <a class="dropdown-item" href="{% url 'groundhog_logbook:charts_by_year' %}"> By Year</a> |
            <a class="dropdown-item" href="{% url 'groundhog_logbook:charts_by_temperature' %}"> By Temperature</a> |
            <a class="dropdown-item" href="{% url 'groundhog_logbook:charts_by_cloud_level' %}"> By Cloud Level</a> |
            <a class="dropdown-item" href="{% url 'groundhog_logbook:charts_by_remover' %}"> By Remover</a> |
            <a class="dropdown-item" href="{% url 'groundhog_logbook:charts_by_caliber' %}"> By Caliber</a> |
            <a class="dropdown-item" href="{% url 'groundhog_logbook:charts_by_distance' %}"> By Distance</a>
        </div>
    </div>
</div>

<br />

<div class="row ben_format_pretty">
    <div align="center">
        <div>{{ graph_message }}</div>
        <div class='col-sm-12'>
            <div class='col-sm-6' style="width:100%"><canvas id="myChart"></canvas></div>
        </div>
    </div>
</div>

{% endblock content %}

imrunicorn/groundhog_logbook/templates/groundhog_logbook/groundhog_pie_chart.html
{% extends "imrunicorn/layout.html" %}

{% block extra_head %}

<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>

<script src="https://kit.fontawesome.com/9a11d62cbf.js" crossorigin="anonymous"></script>
<style>
    /* DivTable.com */
.divTable{
	display: table;
	width: 50%;
}
.divTableRow {
	display: table-row;
}
.divTableHeading {
	background-color: #EEE;
	display: table-header-group;
}
.divTableCell, .divTableHead {
	border: 1px dashed #999999;
	display: table-cell;
	padding: 3px 10px;
}
.divTableHeading {
	background-color: #EEE;
	display: table-header-group;
	font-weight: bold;
}
.divTableFoot {
	background-color: #EEE;
	display: table-footer-group;
	font-weight: bold;
}
.divTableBody {
	display: table-row-group;
}
</style>
{% endblock %}


{% block content %}
{% load humanize %}


<div class="jumbotron">
    <h1>{{ title }}</h1>
    <p class="lead">{{ blurb }}</p>
</div>


{% if logs != None %}

<div class="row ben_format_pretty">
    <div class='post-body entry-content' id='post-body-3156955225064661913' itemprop='description articleBody'>
        <div style="text-align: left;font-family:times new roman;">

            This isn't really a <i>scoreboard</i> per say but more of a way to show who is doing the most removals. It
            also gives me a chance to do something different code wise to get the site to display what I want.

            <br /><br />


            <div class="divTable row ben_format_pretty">
            I'm going to add a graph that shows the number of removals by hour. For now, here's a scoreboard.
        </div>



            {% comment %}
            This will build a little table of the top X removers.
            {% endcomment %}
        <div class="divTable row ben_format_pretty">
            <div class="divTableBody">
                {% for log in logs %}
                <div class="divTableRow">
                    <div class="divTableCell"># {{ forloop.counter }}</div>
                    <div class="divTableCell"><a href="{% url 'groundhog_logbook:all_groundhog_removals' %}{{ log.shooter }}">
                            {{ log.shooter__username|title }}</a></div>
                    <div class="divTableCell">[Count: {{ log.removals }}]</div>
                </div>
                {% endfor %}
            </div>
        </div>



        </div>

    </div>
</div>
{% else %}
<div class="row ben_format_pretty">
    <div class='post-body entry-content' id='post-body-3156955225064661913' itemprop='description articleBody'>
        <div style="text-align: left;font-family:times new roman;">
            Nothing is dead... yet.
        </div>

    </div>
</div>
{% endif %}


{% endblock %}